
baseurl = "http://secretdeveloper.github.io/"
languageCode = "en-us"
title = "Another blog with random, unripenend thoughts."
disqusShortname = "secretdevelopernet"
googleAnalytics = "UA-6023272-11"
theme = "tale"

[author]
    name = "Gary Kenneally - @SecretDeveloper"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params]
    author= "Gary Kenneally"
	twitter = "@secretdeveloper"
	github = "secretdeveloper"
	gratipay = "SecretDeveloper"
	description = "Gary Kenneally - @SecretDeveloper"
	authortwitter = "@secretdeveloper"
	authorname = "Gary Kenneally"

[taxonomies]
  category = "categories"
  tag = "tags"
